services:
  test:
    build: ./
    container_name: "iperf3"
    ports:
      - 50001:5001/tcp
      - 50001:5001/udp
    networks:
      - public
    dns_search: .
networks:
  public:
    driver: bridge
